Controllers/AlquilerVentasController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BaseUsuario.Models;

namespace BaseUsuario.Controllers
{
    public class AlquilerVentasController : Controller
    {
        private readonly BaseUsuarioContext _context;

        public AlquilerVentasController(BaseUsuarioContext context)
        {
            _context = context;
        }

        // GET: AlquilerVentas
        public async Task<IActionResult> Index()
        {
            var baseUsuarioContext = _context.AlquilerVenta.Include(a => a.Peliculas).Include(a => a.Usuarios);
            return View(await baseUsuarioContext.ToListAsync());
        }

        // GET: AlquilerVentas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alquilerVenta = await _context.AlquilerVenta
                .Include(a => a.Peliculas)
                .Include(a => a.Usuarios)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (alquilerVenta == null)
            {
                return NotFound();
            }

            return View(alquilerVenta);
        }

        // GET: AlquilerVentas/Create
        public IActionResult Create()
        {
            ViewData["PeliculasId"] = new SelectList(_context.Set<Peliculas>(), "Id", "Id");
            ViewData["UsuariosId"] = new SelectList(_context.Set<Usuarios>(), "Id", "Id");
            return View();
        }

        // POST: AlquilerVentas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,alq_com,precio,created_at,devolucion,PeliculasId,UsuariosId")] AlquilerVenta alquilerVenta)
        {
            if (ModelState.IsValid)
            {
                _context.Add(alquilerVenta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PeliculasId"] = new SelectList(_context.Set<Peliculas>(), "Id", "Id", alquilerVenta.PeliculasId);
            ViewData["UsuariosId"] = new SelectList(_context.Set<Usuarios>(), "Id", "Id", alquilerVenta.UsuariosId);
            return View(alquilerVenta);
        }

        // GET: AlquilerVentas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alquilerVenta = await _context.AlquilerVenta.FindAsync(id);
            if (alquilerVenta == null)
            {
                return NotFound();
            }
            ViewData["PeliculasId"] = new SelectList(_context.Set<Peliculas>(), "Id", "Id", alquilerVenta.PeliculasId);
            ViewData["UsuariosId"] = new SelectList(_context.Set<Usuarios>(), "Id", "Id", alquilerVenta.UsuariosId);
            return View(alquilerVenta);
        }

        // POST: AlquilerVentas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,alq_com,precio,created_at,devolucion,PeliculasId,UsuariosId")] AlquilerVenta alquilerVenta)
        {
            if (id != alquilerVenta.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(alquilerVenta);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlquilerVentaExists(alquilerVenta.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PeliculasId"] = new SelectList(_context.Set<Peliculas>(), "Id", "Id", alquilerVenta.PeliculasId);
            ViewData["UsuariosId"] = new SelectList(_context.Set<Usuarios>(), "Id", "Id", alquilerVenta.UsuariosId);
            return View(alquilerVenta);
        }

        // GET: AlquilerVentas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alquilerVenta = await _context.AlquilerVenta
                .Include(a => a.Peliculas)
                .Include(a => a.Usuarios)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (alquilerVenta == null)
            {
                return NotFound();
            }

            return View(alquilerVenta);
        }

        // POST: AlquilerVentas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var alquilerVenta = await _context.AlquilerVenta.FindAsync(id);
            _context.AlquilerVenta.Remove(alquilerVenta);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AlquilerVentaExists(int id)
        {
            return _context.AlquilerVenta.Any(e => e.Id == id);
        }
    }
}

Controllers/ListadoController.cs
using BaseUsuario.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BaseUsuario.Controllers
{
    public class ListadosController : Controller
    {

        private readonly BaseUsuarioContext _context;

        public ListadosController(BaseUsuarioContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Prueba()
        {
            return View();
        }


        public async Task<IActionResult> ListaStock(int tipo)
        {
            ViewBag.Tipo = tipo;

            if (tipo == 1)
            {
                var sl = await _context.Peliculas.Where(b => b.cant_disponibles_alquiler > 0)
                    .Select(b => new Peliculas
                    {
                        Id = b.Id,
                        txt_desc = b.txt_desc,
                        cant_disponibles_alquiler = b.cant_disponibles_alquiler
                    })
                    .ToListAsync();
                return View(sl);
            }
            else if (tipo == 2)
            {
                var sl = await _context.Peliculas.Where(b => b.cant_disponibles_venta > 0)
                    .Select(b => new Peliculas
                    {
                        Id = b.Id,
                        txt_desc = b.txt_desc,
                        cant_disponibles_venta = b.cant_disponibles_venta
                    })
                    .ToListAsync();
                return View(sl);
            }
            else
            {
                return BadRequest("No se encontro el tipo");
            }



        }
        //Listado de pelicuals alquiladas

        //var peli = (from a in _context.AlquilerVenta
        //            join u in _context.Users on a.cod_usuario equals u.Id into ords
        //            from o in ords

        //            join p in _context.Peliculas on a.cod_pelicula equals p.Id into emps
        //            from q in emps
        //            select new
        //            {
        //                Id = a.Id,
        //                usuario = o.txt_nombre,
        //                alq_com = 1,
        //                pelicula = q.txt_desc, //"E", // q.txt_desc,
        //                precio = a.precio,
        //                created_at = a.created_at,
        //                devolucion = a.devolucion
        //            });
        public class modelo_listaPelAlq
        {
            public int Id { get; set; }
            public string Peli { get; set; }
            public string Usuario { get; set; }

            public string Precio { get; set; }
            public decimal Count { get; set; }
            public Decimal Suma { get; set; }
            public DateTime Fecha { get; set; }
        }

        public async Task<IActionResult> ListaPelAlq()
        {
            var sl = (from a in _context.AlquilerVenta
                      where a.alq_com == 1
                      join p in _context.Peliculas on a.PeliculasId equals p.Id into ords
                      from o in ords
                      join u in _context.Usuarios on a.UsuariosId equals u.Id into user
                      from us in user
                      select new modelo_listaPelAlq
                      {
                          Id = a.Id,
                          Peli = o.txt_desc,
                          Usuario = us.Nombre,
                          Precio = o.precio_alquiler.ToString(),
                          Fecha = a.created_at
                      });

            return View(sl);

        }
        // Listado pelicuals no devueltas
        public async Task<IActionResult> ListaPelAlqNoDvueltas()
        {
            var sl = (from a in _context.AlquilerVenta
                      where a.devolucion == -1 && a.alq_com == 1
                      join p in _context.Peliculas on a.PeliculasId equals p.Id into ords
                      from o in ords
                      join u in _context.Usuarios on a.UsuariosId equals u.Id into user
                      from us in user
                      select new modelo_listaPelAlq
                      {
                          Id = a.Id,
                          Peli = o.txt_desc,
                          Usuario = us.Nombre
                      });

            return View(sl);

        }
        //var suma = (from sol in solicitud.Desplazamientos
        //            from con in sol.ConcepTrayec
        //            group con by new { con.IdConcepto, con.IdCategoria } into g
        //            select new
        //            {
        //                IdConcepto = g.Key.IdConcepto,
        //                IdCategoria = g.Key.IdCategoria,
        //                Valor = g.Sum(x => x.Valor)
        //            }).ToList();
        public IActionResult ListaPelisRecaudado()
        {
            var sl = (from alq in _context.AlquilerVenta
                      group alq by new { alq.PeliculasId } into g
                      select new modelo_listaPelAlq
                      {
                          Peli = g.Key.PeliculasId.ToString(),
                          Suma = (decimal)g.Sum(x => x.precio),
                          Count = g.Count()


                      });
            return View(sl);
        }
    }
}

Controllers/LoginController.cs
using BaseUsuario.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;
using BaseUsuario.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;

namespace BaseUsuario.Controllers
{
    public class LoginController : Controller
    {

        private readonly BaseUsuarioContext _context;
        public LoginController( BaseUsuarioContext context)
        {
            
            _context = context;
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModels objLoginModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                   
                    var usuario = _context.Usuarios.Where(x => x.UserName == objLoginModel.UserName && x.Password == objLoginModel.Password).SingleOrDefault();// _context.Usuarios.Include("Rols").Where(x => x.UserName == objLoginModel.UserName && x.Password == objLoginModel.Password).SingleOrDefault();

                    if (usuario != null)
                    {
                        string Role = _context.Rols.Where(x => x.Id == usuario.RolsId).SingleOrDefault().Descripcion;
                        if (Role == null)
                        {
                            return NotFound(new JObject() { { "StatusCode", 404 }, { "Message", "Usuario no encontrado" } });
                        }
                        //var claims = new List<Claim>() {
                        //new Claim(ClaimTypes.NameIdentifier, Convert.ToString(usuario.id)),
                        //new Claim(ClaimTypes.Name, Convert.ToString(usuario.Nombre)),
                        //new Claim(ClaimTypes.Role, Convert.ToString(usuario.Rol_id))
                        //};

                        var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme, ClaimTypes.Name, ClaimTypes.Role);

                        identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, Convert.ToString(usuario.Id)));
                        identity.AddClaim(new Claim(ClaimTypes.Name, Convert.ToString(usuario.Nombre)));
                        identity.AddClaim(new Claim(ClaimTypes.Role, Role));
                        identity.AddClaim(new Claim("Dato", "Valor"));
                        var principal = new ClaimsPrincipal(identity);
                        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal,
                            new AuthenticationProperties { ExpiresUtc = DateTime.Now.AddMinutes(1), IsPersistent = true });

                        // si tengo muchos roles asociados al usuario pudedo aregarlos con foreach, solo de referencia, no se aplica a este proyecto
                        //foreach(var Rol in usuario.Rols)
                        //{
                        //    identity.AddClaim(new Claim(ClaimTypes.Role, Rol.Descripcion));
                        //}

                        //SessionHelper.AddUserToSession(usuario.id.ToString());
                        return RedirectToAction("PeliculasAV", "Home");
                    }
                    else
                    {
                        ViewBag.Message = "Usuario o contraseña No validos";
                        
                        return View(objLoginModel);
                    }

                }
                catch (Exception e)
                {
                    ViewBag.Message = "Excepción no Controlada " + e;
                    return View();
                    //return BadRequest(e);
                }
            }
            ViewBag.Message = "Usuario o contraseña Salio por validacion de modelo";
            return View();

        }
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> Register()
        {
            var rols = await _context.Rols.ToListAsync();
            ViewData["RolId"] = new SelectList(rols, "Id", "Descripcion");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register([Bind("UserName,Password,Apellido, NroDocumento, Nombre,Email, RolsId")] Usuarios usuarios)
        {
            if (ModelState.IsValid)
            {
                //ViewData["Rols"] = new SelectList(_context.Set<Rols>(), "Descripcion", "Descripcion");
                usuarios.SnActivo = -1;
                _context.Add(usuarios);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
                //return View();
            }
            ViewData["RolId"] = new SelectList(_context.Set<Rols>(), "Id", "Descripcion", usuarios.RolsId);
            return View();

        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return Redirect("/");
        }
        public IActionResult AccessDenied()
        {
            
            return View();
        }
    }
}

Views/Shared/EncabezadoListados.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Listados</h1>

<h2>Presione el listado que le interesa</h2>

<input type="button" value="Stock Venta" onclick="location.href='@Url.Action("ListaStock", "Listados",  new {tipo = 2 })'" />
<input type="button" value="Stock Alquiler" onclick="location.href='@Url.Action("ListaStock", "Listados",  new {tipo = 1 })'" />
<input type="button" value="Peliculas alquiladas" onclick="location.href='@Url.Action("ListaPelAlq", "Listados")'" />
<input type="button" value="Ver Peliculas No Devueltas" onclick="location.href='@Url.Action("ListaPelAlqNoDvueltas", "Listados")'" />
<input type="button" value="Ver Total Alquiladas y Recaudacion" onclick="location.href='@Url.Action("ListaPelisRecaudado", "Listados")'" />

Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity;


@if (User.Identity.IsAuthenticated)
{

    <ul class="nav navbar-nav navbar-right">
        @if(User.IsInRole("Admin")){
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Listados" asp-action="Index">Listados</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="AlquilerVentas" asp-action="Index">AlquilerVentas</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Register">  Register</a>
        </li>
        }
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">  Logout</a>
        </li>
    </ul>

}
else
{
    <ul class="nav navbar-nav navbar-right">
        @*<li><a asp-area="" asp-controller="Account" asp-action="Register">Register</a></li>*@
        @* <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Register">  Register</a>
            </li>*@
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">  Login</a>
        </li>
    </ul>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BaseUsuario</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BaseUsuario.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <div class="container">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Video Club</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="PeliculasAV">Peliculas</a>
                        </li>
                      

                    </ul>
                      @Html.Partial("LoginPartial")
                </div>
            </div>
        </nav>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - VideoClub Todos los derechos reservados Esteban- <a asp-area="" asp-controller="Home" asp-action="Index|">www.egdesarrollos.com</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>